ALTER TABLE alarms DROP COLUMN state;
DROP TABLE wakes CASCADE;
DROP TABLE dismisses CASCADE;
DROP TABLE snoozes CASCADE;
DROP TABLE user_orgs CASCADE;
DROP TABLE orgs CASCADE;
DROP TABLE user_settings CASCADE;
