#!/bin/sh

echo "Hello, "$USER".  This script will register you in Michel's friends database."
echo -n "Enter your name and press [ENTER]: "
read name
echo -n "Enter your gender and press [ENTER]: "
read gender
echo

if [ "$gender" == "m" ]; then
  echo "You are added to Michel's friends list."
  exit 1
else
  echo "You are a noob go home"
  exit 1
fi

#grep -i "$name" "$friends"
